"""GVid Taut contracts, draft v0.2: flat graph and editor/media/render services.

Semantic validation and delivery rules are specified in the accompanying design doc.
"""

from taut.ir.dsl import BOOL, INT, STR, Enum, F, List, Map, Msg, Params, Ref, method, option, schema, service

SCHEMA = schema(
    option.max_depth(16),
    option.max_encoded_len(16777216),
    service("RenderGraph",
        method("snapshot", role="query",
               params=Params(project_id=STR, graph_id=STR), out=Ref.GraphSnapshotDelivery),
        method("apply", role="in", params=Params(request=Ref.ApplyGraphBatch), out=Ref.EditAck),
        method("changes", role="out", shape="log",
               params=Params(project_id=STR, graph_id=STR,
                             authority_incarnation_id=STR, after_revision=INT),
               out=Ref.GraphChangeEvent)),
    service("Editor",
        method("editor.insert_source_span", role="in",
               params=Params(request=Ref.InsertSourceSpan), out=Ref.EditorAck),
        method("editor.undo", role="in",
               params=Params(request=Ref.HistoryIntent), out=Ref.EditorAck),
        method("editor.redo", role="in",
               params=Params(request=Ref.HistoryIntent), out=Ref.EditorAck),
        method("editor.history", role="query",
               params=Params(project_id=STR, graph_id=STR, sequence_id=STR,
                             authority_incarnation_id=STR),
               out=Ref.HistoryState)),
    service("MediaCatalog",
        method("catalog.snapshot", role="query",
               params=Params(project_id=STR, authority_incarnation_id=STR),
               out=Ref.CatalogSnapshot),
        method("catalog.changes", role="out", shape="log",
               params=Params(project_id=STR, authority_incarnation_id=STR,
                             after_catalog_revision=INT),
               out=Ref.CatalogChangeEvent),
        method("catalog.frame_at_index", role="query",
               params=Params(request=Ref.FrameIndexQuery),
               out=Ref.FrameIndexResult)),
    service("AssetBindings",
        method("bindings.snapshot", role="query",
               params=Params(project_id=STR, graph_id=STR), out=Ref.BindingSnapshot),
        method("bindings.rebind", role="in",
               params=Params(request=Ref.RebindSlot), out=Ref.BindingAck),
        method("bindings.changes", role="out", shape="log",
               params=Params(project_id=STR, graph_id=STR,
                             authority_incarnation_id=STR, after_binding_revision=INT),
               out=Ref.BindingChangeEvent)),
    service("Preview",
        method("preview.source_frame", role="query",
               params=Params(request=Ref.SourcePreviewRequest), out=Ref.SourcePreviewResult),
        method("preview.sequence_frame", role="query",
               params=Params(request=Ref.SequencePreviewRequest), out=Ref.SequencePreviewResult),
        method("preview.cancel", role="in",
               params=Params(request=Ref.CancelPreview), out=Ref.ResourceActionAck),
        method("preview.release", role="in",
               params=Params(request=Ref.ReleaseResource), out=Ref.ResourceActionAck)),
    service("ExportJobs",
        method("export.submit", role="in",
               params=Params(request=Ref.ExportJobRequest), out=Ref.ExportJobAck),
        method("export.lookup", role="query",
               params=Params(request=Ref.ExportLookupQuery),
               out=Ref.ExportLookupResult),
        method("export.events", role="out", shape="log",
               params=Params(request=Ref.ExportEventsQuery),
               out=Ref.ExportEventDelivery),
        method("export.status", role="query",
               params=Params(request=Ref.ExportStatusQuery),
               out=Ref.ExportStatusResult),
        method("export.cancel", role="in",
               params=Params(request=Ref.CancelExportJob), out=Ref.ExportCancelAck)),
    service("ProjectAuthority",
        method("authority.open", role="query",
               params=Params(project_id=STR), out=Ref.ProjectOpen),
        method("authority.acquire_writer", role="in",
               params=Params(request=Ref.AcquireWriter), out=Ref.WriterLease)),
    MediaKind=Enum(video=1, audio=2, text=3),
    NodeKind=Enum(source=1, effect=2, composite=3, transition=4, title=5, output=6, silence=7),
    ParamKind=Enum(integer=1, rational=2, boolean=3, text=4),
    EditKind=Enum(put_node=1, remove_node=2, put_edge=3, remove_edge=4,
                  put_track=5, remove_track=6, put_sequence=7, remove_sequence=8,
                  put_slot=9, remove_slot=10),
    AckStatus=Enum(accepted=1, stale=2, invalid=3, unauthorized=4),
    GraphEventKind=Enum(ready=1, change=2, heartbeat=3, recovery_required=4),
    PlacementMode=Enum(ripple_track=1, overwrite_track=2),
    EditorStatus=Enum(accepted=1, stale_graph=2, stale_binding=3, invalid_range=4,
                      locked_track=5, unsupported_ripple_scope=6, unauthorized=7,
                      invalid_command=8, unsupported_schema=9, recovery_required=10),
    BindingStatus=Enum(accepted=1, stale_graph=2, stale_binding=3, incompatible_media=4,
                       invalid_policy=5, unauthorized=6, invalid_command=7),
    BindingEventKind=Enum(ready=1, change=2, heartbeat=3, recovery_required=4),
    CatalogEventKind=Enum(ready=1, change=2, heartbeat=3, recovery_required=4),
    AssetAvailability=Enum(online=1, missing=2, changed=3, offline=4),
    IndexStatus=Enum(pending=1, ready=2, failed=3),
    FrameLookupStatus=Enum(ready=1, pending=2, out_of_range=3,
                           unavailable=4, stale_version=5, failed=6),
    DurationPolicy=Enum(exact=1, trim=2, pad=3),
    FrameRatePolicy=Enum(source_pts=1, conform=2),
    AspectPolicy=Enum(reject=1, fit=2, crop=3),
    ChannelPolicy=Enum(reject=1, map=2),
    MissingRangePolicy=Enum(reject=1, gap=2),
    PreviewFidelity=Enum(exact=1, proxy=2),
    PreviewStatus=Enum(ready=1, cancelled=2, stale_graph=3, stale_binding=4,
                       unsupported=5, failed=6, stale_asset=7),
    AuthorityState=Enum(ready=1, read_only_future_version=2,
                        recovery_required=3, closed=4),
    LeaseStatus=Enum(granted=1, held_by_other=2, stale_incarnation=3,
                     read_only=4, recovery_required=5),
    ResourceActionStatus=Enum(accepted=1, unknown=2, expired=3, unauthorized=4),
    ExportProvenance=Enum(governed_host=1, standalone_import=2),
    ExportSubmitStatus=Enum(accepted=1, stale_context=2, invalid=3,
                            unauthorized=4, unsupported=5, capacity=6,
                            recovery_required=7, destination_busy=8,
                            idempotency_conflict=9, retired_request=10),
    ExportDestinationPolicy=Enum(fail_if_exists=1, replace_existing=2),
    ExportLookupStatus=Enum(found=1, unavailable=2, stale_context=3,
                            retired_request=4),
    ExportStatusResultStatus=Enum(found=1, unavailable=2, stale_context=3),
    ExportEventDeliveryStatus=Enum(event=1, unavailable=2, stale_context=3),
    ExportJobState=Enum(queued=1, preparing=2, running=3, verifying=4,
                        succeeded=5, failed=6, cancelled=7, interrupted=8),
    ExportEventKind=Enum(ready=1, state_change=2, progress=3, warning=4,
                         heartbeat=5, recovery_required=6),
    # Former cancel codes 3 (unknown) and 4 (unauthorized) are reserved.
    ExportCancelStatus=Enum(accepted=1, already_terminal=2,
                            stale_context=5, unavailable=6),
    Rational=Msg(numerator=F(1, INT), denominator=F(2, INT), next_id=3),
    TimeRange=Msg(start=F(1, Ref.Rational), end=F(2, Ref.Rational), next_id=3),
    ParamValue=Msg(kind=F(1, Ref.ParamKind), integer=F(2, INT, optional=True),
                   rational=F(3, Ref.Rational, optional=True),
                   boolean=F(4, BOOL, optional=True),
                   text=F(5, STR, optional=True), next_id=6),
    SourcePayload=Msg(slot_id=F(1, STR), stream_id=F(2, STR),
                      source_range=F(3, Ref.TimeRange),
                      speed=F(4, Ref.Rational), next_id=5),
    EffectPayload=Msg(effect_id=F(1, STR), effect_version=F(2, INT),
                      params=F(3, Map(STR, Ref.ParamValue)), next_id=4),
    CompositePayload=Msg(blend_id=F(1, STR), next_id=2),
    TransitionPayload=Msg(transition_id=F(1, STR), transition_version=F(2, INT),
                          params=F(3, Map(STR, Ref.ParamValue)), next_id=4),
    TitlePayload=Msg(text=F(1, STR), style_id=F(2, STR), next_id=3),
    OutputPayload=Msg(output_media=F(1, Ref.MediaKind), next_id=2),
    Node=Msg(id=F(1, STR), kind=F(2, Ref.NodeKind), media=F(3, Ref.MediaKind),
             sequence_id=F(4, STR), track_id=F(5, STR, optional=True),
             timeline_range=F(6, Ref.TimeRange, optional=True),
             source=F(7, Ref.SourcePayload, optional=True),
             effect=F(8, Ref.EffectPayload, optional=True),
             composite=F(9, Ref.CompositePayload, optional=True),
             transition=F(10, Ref.TransitionPayload, optional=True),
             title=F(11, Ref.TitlePayload, optional=True),
             output=F(12, Ref.OutputPayload, optional=True), next_id=13),
    Edge=Msg(id=F(1, STR), from_node=F(2, STR), from_port=F(3, STR),
             to_node=F(4, STR), to_port=F(5, STR),
             order_key=F(6, STR, optional=True), next_id=7),
    Track=Msg(id=F(1, STR), sequence_id=F(2, STR), media=F(3, Ref.MediaKind),
              order_key=F(4, STR), enabled=F(5, BOOL), next_id=6),
    Sequence=Msg(id=F(1, STR), video_root=F(2, STR, optional=True),
                 audio_root=F(3, STR, optional=True),
                 range=F(4, Ref.TimeRange), next_id=5),
    AssetSlot=Msg(id=F(1, STR), expected_media=F(2, Ref.MediaKind),
                  expected_duration=F(3, Ref.Rational, optional=True),
                  expected_fingerprint=F(4, STR, optional=True), next_id=5),
    GraphSnapshot=Msg(schema_major=F(1, INT), schema_minor=F(2, INT),
        graph_id=F(3, STR), project_id=F(4, STR), revision=F(5, INT),
        semantic_version=F(6, INT), sequences=F(7, Map(STR, Ref.Sequence)),
        tracks=F(8, Map(STR, Ref.Track)), nodes=F(9, Map(STR, Ref.Node)),
        edges=F(10, Map(STR, Ref.Edge)), slots=F(11, Map(STR, Ref.AssetSlot)),
        next_id=12),
    GraphSemantics=Msg(schema_major=F(1, INT), schema_minor=F(2, INT),
        semantic_version=F(3, INT), sequences=F(4, Map(STR, Ref.Sequence)),
        tracks=F(5, Map(STR, Ref.Track)), nodes=F(6, Map(STR, Ref.Node)),
        edges=F(7, Map(STR, Ref.Edge)), slots=F(8, Map(STR, Ref.AssetSlot)),
        next_id=9),
    GraphSnapshotDelivery=Msg(snapshot=F(1, Ref.GraphSnapshot),
                              authority_incarnation_id=F(2, STR), next_id=3),
    EditOperation=Msg(kind=F(1, Ref.EditKind), target_id=F(2, STR),
        node=F(3, Ref.Node, optional=True), edge=F(4, Ref.Edge, optional=True),
        track=F(5, Ref.Track, optional=True),
        sequence=F(6, Ref.Sequence, optional=True),
        slot=F(7, Ref.AssetSlot, optional=True), next_id=8),
    EditBatch=Msg(project_id=F(1, STR), graph_id=F(2, STR),
        command_id=F(3, STR), expected_revision=F(4, INT),
        undo_group_id=F(5, STR), operations=F(6, List(Ref.EditOperation)),
        next_id=7),
    ApplyGraphBatch=Msg(batch=F(1, Ref.EditBatch),
        authority_incarnation_id=F(2, STR),
        writer_capability=F(3, STR), next_id=4),
    AffectedInterval=Msg(sequence_id=F(1, STR),
                         range=F(2, Ref.TimeRange), next_id=3),
    ChangeFootprint=Msg(intervals=F(1, List(Ref.AffectedInterval)),
        node_ids=F(2, List(STR)), slot_ids=F(3, List(STR)),
        full_invalidation=F(4, BOOL), next_id=5),
    EditAck=Msg(command_id=F(1, STR), status=F(2, Ref.AckStatus),
        revision=F(3, INT), semantic_digest=F(4, STR, optional=True),
        reason=F(5, STR, optional=True),
        footprint=F(6, Ref.ChangeFootprint, optional=True),
        project_id=F(7, STR), graph_id=F(8, STR),
        authority_incarnation_id=F(9, STR),
        replayed=F(10, BOOL), next_id=11),
    AcceptedChange=Msg(graph_id=F(1, STR), command_id=F(2, STR),
        from_revision=F(3, INT), to_revision=F(4, INT),
        operations=F(5, List(Ref.EditOperation)),
        footprint=F(6, Ref.ChangeFootprint), project_id=F(7, STR),
        next_id=8),
    GraphChangeEvent=Msg(kind=F(1, Ref.GraphEventKind),
        project_id=F(2, STR), graph_id=F(3, STR),
        authority_incarnation_id=F(4, STR), revision=F(5, INT),
        first_available_revision=F(6, INT),
        change=F(7, Ref.AcceptedChange, optional=True),
        reason=F(8, STR, optional=True), next_id=9),
    InsertSourceSpan=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        graph_id=F(3, STR), sequence_id=F(4, STR),
        authority_incarnation_id=F(5, STR), command_id=F(6, STR),
        expected_revision=F(7, INT), target_track_id=F(8, STR),
        timeline_at=F(9, Ref.Rational), placement=F(10, Ref.PlacementMode),
        slot_id=F(11, STR, optional=True), stream_id=F(12, STR),
        source_range=F(13, Ref.TimeRange), speed=F(14, Ref.Rational),
        expected_binding_set_id=F(15, STR), undo_group_id=F(16, STR),
        writer_capability=F(17, STR),
        registered_asset_id=F(18, STR, optional=True),
        asset_version_id=F(19, STR, optional=True), next_id=20),
    HistoryIntent=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        graph_id=F(3, STR), sequence_id=F(4, STR),
        authority_incarnation_id=F(5, STR), command_id=F(6, STR),
        expected_revision=F(7, INT), target_undo_group_id=F(8, STR),
        expected_binding_set_id=F(9, STR),
        writer_capability=F(10, STR), next_id=11),
    UndoGroupSummary=Msg(group_id=F(1, STR), sequence_id=F(2, STR),
        label=F(3, STR), command_id=F(4, STR), next_id=5),
    HistoryState=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        graph_id=F(3, STR), sequence_id=F(4, STR),
        authority_incarnation_id=F(5, STR), revision=F(6, INT),
        undo_groups=F(7, List(Ref.UndoGroupSummary)),
        redo_groups=F(8, List(Ref.UndoGroupSummary)),
        can_undo=F(9, BOOL), can_redo=F(10, BOOL), next_id=11),
    EditorAck=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        graph_id=F(3, STR), sequence_id=F(4, STR),
        authority_incarnation_id=F(5, STR), command_id=F(6, STR),
        status=F(7, Ref.EditorStatus), replayed=F(8, BOOL),
        revision=F(9, INT), binding_set_id=F(10, STR),
        footprint=F(11, Ref.ChangeFootprint, optional=True),
        diagnostic_id=F(12, STR, optional=True),
        binding_revision=F(13, INT),
        created_slot_id=F(14, STR, optional=True), next_id=15),
    CatalogStream=Msg(id=F(1, STR), media=F(2, Ref.MediaKind),
        duration=F(3, Ref.Rational), pts_origin=F(4, Ref.Rational),
        frame_count=F(5, INT, optional=True),
        frame_index_id=F(6, STR, optional=True),
        index_status=F(7, Ref.IndexStatus), next_id=8),
    RegisteredAsset=Msg(id=F(1, STR), version_id=F(2, STR),
        content_fingerprint=F(3, STR), display_name=F(4, STR),
        streams=F(5, Map(STR, Ref.CatalogStream)),
        availability=F(6, Ref.AssetAvailability),
        diagnostic_id=F(7, STR, optional=True), next_id=8),
    CatalogSnapshot=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        authority_incarnation_id=F(3, STR), catalog_revision=F(4, INT),
        assets=F(5, Map(STR, Ref.RegisteredAsset)), next_id=6),
    CatalogChange=Msg(project_id=F(1, STR),
        from_catalog_revision=F(2, INT), to_catalog_revision=F(3, INT),
        upserts=F(4, Map(STR, Ref.RegisteredAsset)),
        removed_asset_ids=F(5, List(STR)), next_id=6),
    CatalogChangeEvent=Msg(kind=F(1, Ref.CatalogEventKind),
        project_id=F(2, STR), authority_incarnation_id=F(3, STR),
        catalog_revision=F(4, INT), first_available_revision=F(5, INT),
        change=F(6, Ref.CatalogChange, optional=True),
        reason=F(7, STR, optional=True), next_id=8),
    FrameIndexQuery=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        authority_incarnation_id=F(3, STR), registered_asset_id=F(4, STR),
        asset_version_id=F(5, STR), stream_id=F(6, STR),
        frame_index=F(7, INT), next_id=8),
    FrameIndexResult=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        authority_incarnation_id=F(3, STR), registered_asset_id=F(4, STR),
        asset_version_id=F(5, STR), stream_id=F(6, STR),
        frame_index=F(7, INT), status=F(8, Ref.FrameLookupStatus),
        pts=F(9, Ref.Rational, optional=True),
        frame_count=F(10, INT, optional=True),
        content_fingerprint=F(11, STR, optional=True),
        diagnostic_id=F(12, STR, optional=True), next_id=13),
    AssetBinding=Msg(slot_id=F(1, STR), registered_asset_id=F(2, STR),
        asset_version_id=F(3, STR), stream_id=F(4, STR),
        content_fingerprint=F(5, STR), media=F(6, Ref.MediaKind),
        duration=F(7, Ref.Rational), next_id=8),
    BindingSnapshot=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        graph_id=F(3, STR), authority_incarnation_id=F(4, STR),
        binding_set_id=F(5, STR), binding_revision=F(6, INT),
        bindings=F(7, Map(STR, Ref.AssetBinding)), next_id=8),
    BindingPolicy=Msg(duration=F(1, Ref.DurationPolicy),
        frame_rate=F(2, Ref.FrameRatePolicy), aspect=F(3, Ref.AspectPolicy),
        channels=F(4, Ref.ChannelPolicy),
        missing_range=F(5, Ref.MissingRangePolicy), next_id=6),
    RebindSlot=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        graph_id=F(3, STR), authority_incarnation_id=F(4, STR),
        command_id=F(5, STR), expected_graph_revision=F(6, INT),
        expected_binding_set_id=F(7, STR), slot_id=F(8, STR),
        registered_asset_id=F(9, STR), asset_version_id=F(10, STR),
        stream_id=F(11, STR), policy=F(12, Ref.BindingPolicy),
        writer_capability=F(13, STR), next_id=14),
    BindingAck=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        graph_id=F(3, STR), authority_incarnation_id=F(4, STR),
        command_id=F(5, STR), status=F(6, Ref.BindingStatus),
        replayed=F(7, BOOL), graph_revision=F(8, INT),
        binding_set_id=F(9, STR), binding_revision=F(10, INT),
        footprint=F(11, Ref.ChangeFootprint, optional=True),
        diagnostic_id=F(12, STR, optional=True), next_id=13),
    BindingChange=Msg(project_id=F(1, STR), graph_id=F(2, STR),
        from_binding_revision=F(3, INT), to_binding_revision=F(4, INT),
        from_binding_set_id=F(5, STR), to_binding_set_id=F(6, STR),
        changed_slot_ids=F(7, List(STR)),
        footprint=F(8, Ref.ChangeFootprint), next_id=9),
    BindingChangeEvent=Msg(kind=F(1, Ref.BindingEventKind),
        project_id=F(2, STR), graph_id=F(3, STR),
        authority_incarnation_id=F(4, STR), binding_revision=F(5, INT),
        first_available_revision=F(6, INT),
        change=F(7, Ref.BindingChange, optional=True),
        reason=F(8, STR, optional=True), next_id=9),
    SourcePreviewRequest=Msg(contract_version=F(1, INT),
        project_id=F(2, STR), authority_incarnation_id=F(3, STR),
        registered_asset_id=F(4, STR), asset_version_id=F(5, STR),
        stream_id=F(6, STR), request_id=F(7, STR), viewer_id=F(8, STR),
        cancel_group_id=F(9, STR), at=F(10, Ref.Rational),
        fidelity=F(11, Ref.PreviewFidelity),
        max_edge_px=F(12, INT),
        expected_content_fingerprint=F(13, STR), next_id=14),
    SequencePreviewRequest=Msg(contract_version=F(1, INT),
        project_id=F(2, STR), graph_id=F(3, STR), sequence_id=F(4, STR),
        authority_incarnation_id=F(5, STR), accepted_revision=F(6, INT),
        binding_set_id=F(7, STR), binding_revision=F(8, INT),
        request_id=F(9, STR), viewer_id=F(10, STR),
        cancel_group_id=F(11, STR), at=F(12, Ref.Rational),
        fidelity=F(13, Ref.PreviewFidelity),
        max_edge_px=F(14, INT), next_id=15),
    ResourceDescriptor=Msg(resource_id=F(1, STR), lease_id=F(2, STR),
        mime_type=F(3, STR), width=F(4, INT), height=F(5, INT),
        byte_length=F(6, INT), expires_at_unix_ms=F(7, INT), next_id=8),
    SourcePreviewResult=Msg(contract_version=F(1, INT),
        project_id=F(2, STR), authority_incarnation_id=F(3, STR),
        registered_asset_id=F(4, STR), asset_version_id=F(5, STR),
        stream_id=F(6, STR), request_id=F(7, STR), viewer_id=F(8, STR),
        cancel_group_id=F(9, STR), status=F(10, Ref.PreviewStatus),
        fidelity=F(11, Ref.PreviewFidelity),
        actual_time=F(12, Ref.Rational, optional=True),
        resource=F(13, Ref.ResourceDescriptor, optional=True),
        error_code=F(14, STR, optional=True),
        diagnostic_id=F(15, STR, optional=True),
        content_fingerprint=F(16, STR), next_id=17),
    SequencePreviewResult=Msg(contract_version=F(1, INT),
        project_id=F(2, STR), graph_id=F(3, STR), sequence_id=F(4, STR),
        authority_incarnation_id=F(5, STR), accepted_revision=F(6, INT),
        binding_set_id=F(7, STR), binding_revision=F(8, INT),
        request_id=F(9, STR), viewer_id=F(10, STR),
        cancel_group_id=F(11, STR), status=F(12, Ref.PreviewStatus),
        fidelity=F(13, Ref.PreviewFidelity),
        actual_time=F(14, Ref.Rational, optional=True),
        plan_id=F(15, STR, optional=True),
        resource=F(16, Ref.ResourceDescriptor, optional=True),
        error_code=F(17, STR, optional=True),
        diagnostic_id=F(18, STR, optional=True), next_id=19),
    CancelPreview=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        graph_id=F(3, STR, optional=True), authority_incarnation_id=F(4, STR),
        request_id=F(5, STR), viewer_id=F(6, STR),
        cancel_group_id=F(7, STR), next_id=8),
    ReleaseResource=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        graph_id=F(3, STR, optional=True), authority_incarnation_id=F(4, STR),
        lease_id=F(5, STR), viewer_id=F(6, STR), next_id=7),
    ResourceActionAck=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        graph_id=F(3, STR, optional=True), authority_incarnation_id=F(4, STR),
        action_id=F(5, STR), status=F(6, Ref.ResourceActionStatus),
        next_id=7),
    ExportJobContext=Msg(request_id=F(1, STR),
        provenance=F(2, Ref.ExportProvenance), project_id=F(3, STR),
        graph_id=F(4, STR), sequence_id=F(5, STR),
        authority_incarnation_id=F(6, STR, optional=True),
        local_import_id=F(7, STR, optional=True),
        accepted_revision=F(8, INT), binding_set_id=F(9, STR),
        binding_revision=F(10, INT), profile_id=F(11, STR),
        profile_version=F(12, INT), profile_digest=F(13, STR), next_id=14),
    ExportJobRequest=Msg(contract_version=F(1, INT),
        context=F(2, Ref.ExportJobContext), range=F(3, Ref.TimeRange),
        destination_ref=F(4, STR), allow_software_fallback=F(5, BOOL),
        destination_policy=F(6, Ref.ExportDestinationPolicy), next_id=7),
    ExportJobAck=Msg(contract_version=F(1, INT),
        context=F(2, Ref.ExportJobContext), status=F(3, Ref.ExportSubmitStatus),
        job_id=F(4, STR, optional=True), replayed=F(5, BOOL),
        diagnostic_id=F(6, STR, optional=True), next_id=7),
    ExportProbeSummary=Msg(video_stream_count=F(1, INT),
        audio_stream_count=F(2, INT), duration=F(3, Ref.Rational),
        width=F(4, INT, optional=True), height=F(5, INT, optional=True),
        audio_sample_rate=F(6, INT, optional=True),
        audio_channel_layout=F(7, STR, optional=True), next_id=8),
    ExportResult=Msg(export_record_id=F(1, STR),
        output_artifact_id=F(2, STR), probe_summary=F(3, Ref.ExportProbeSummary),
        output_probe_digest=F(4, STR), destination_generation_id=F(5, STR),
        next_id=6),
    ExportJobEvent=Msg(contract_version=F(1, INT),
        context=F(2, Ref.ExportJobContext), job_id=F(3, STR),
        event_sequence=F(4, INT), first_available_sequence=F(5, INT),
        kind=F(6, Ref.ExportEventKind),
        state=F(7, Ref.ExportJobState, optional=True),
        progress=F(8, Ref.Rational, optional=True),
        result=F(9, Ref.ExportResult, optional=True),
        diagnostic_id=F(10, STR, optional=True), next_id=11),
    ExportEventsQuery=Msg(contract_version=F(1, INT),
        project_id=F(2, STR), job_id=F(3, STR),
        after_event_sequence=F(4, INT),
        caller_incarnation_id=F(5, STR, optional=True),
        local_import_id=F(6, STR, optional=True), next_id=7),
    ExportEventDelivery=Msg(contract_version=F(1, INT),
        project_id=F(2, STR), job_id=F(3, STR),
        status=F(4, Ref.ExportEventDeliveryStatus),
        event=F(5, Ref.ExportJobEvent, optional=True),
        diagnostic_id=F(6, STR, optional=True), next_id=7),
    ExportStatusQuery=Msg(contract_version=F(1, INT),
        project_id=F(2, STR), job_id=F(3, STR),
        caller_incarnation_id=F(4, STR, optional=True),
        local_import_id=F(5, STR, optional=True), next_id=6),
    ExportStatusSnapshot=Msg(contract_version=F(1, INT),
        context=F(2, Ref.ExportJobContext), job_id=F(3, STR),
        state=F(4, Ref.ExportJobState), last_event_sequence=F(5, INT),
        result=F(6, Ref.ExportResult, optional=True),
        diagnostic_id=F(7, STR, optional=True), next_id=8),
    ExportStatusResult=Msg(contract_version=F(1, INT),
        project_id=F(2, STR), job_id=F(3, STR),
        status=F(4, Ref.ExportStatusResultStatus),
        snapshot=F(5, Ref.ExportStatusSnapshot, optional=True),
        diagnostic_id=F(6, STR, optional=True), next_id=7),
    ExportLookupQuery=Msg(contract_version=F(1, INT),
        project_id=F(2, STR), request_id=F(3, STR),
        caller_incarnation_id=F(4, STR, optional=True),
        local_import_id=F(5, STR, optional=True), next_id=6),
    ExportLookupResult=Msg(contract_version=F(1, INT),
        project_id=F(2, STR), request_id=F(3, STR),
        status=F(4, Ref.ExportLookupStatus),
        snapshot=F(5, Ref.ExportStatusSnapshot, optional=True),
        diagnostic_id=F(6, STR, optional=True), next_id=7),
    CancelExportJob=Msg(contract_version=F(1, INT),
        project_id=F(2, STR), job_id=F(3, STR), command_id=F(4, STR),
        caller_incarnation_id=F(5, STR, optional=True),
        local_import_id=F(6, STR, optional=True), next_id=7),
    ExportCancelAck=Msg(contract_version=F(1, INT),
        project_id=F(2, STR), job_id=F(3, STR), command_id=F(4, STR),
        status=F(5, Ref.ExportCancelStatus),
        terminal_state=F(6, Ref.ExportJobState, optional=True), next_id=7),
    ProjectOpen=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        graph_id=F(3, STR, optional=True),
        authority_incarnation_id=F(4, STR),
        state=F(5, Ref.AuthorityState), graph_revision=F(6, INT),
        binding_set_id=F(7, STR, optional=True),
        diagnostic_id=F(8, STR, optional=True), next_id=9),
    AcquireWriter=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        graph_id=F(3, STR), authority_incarnation_id=F(4, STR),
        request_id=F(5, STR), next_id=6),
    WriterLease=Msg(contract_version=F(1, INT), project_id=F(2, STR),
        graph_id=F(3, STR), authority_incarnation_id=F(4, STR),
        request_id=F(5, STR), status=F(6, Ref.LeaseStatus),
        lease_id=F(7, STR, optional=True),
        writer_capability=F(8, STR, optional=True),
        expires_at_unix_ms=F(9, INT, optional=True), next_id=10),
)
