"""GVid flat graph, draft v0.1. Application invariants live in the design doc."""

from taut.ir.dsl import BOOL, INT, STR, Enum, F, List, Map, Msg, Params, Ref, method, option, schema, service

SCHEMA = schema(
    option.max_depth(16),
    option.max_encoded_len(16777216),
    service("RenderGraph",
        method("snapshot", role="query",
               params=Params(project_id=STR, graph_id=STR), out=Ref.GraphSnapshot),
        method("apply", role="in", params=Params(batch=Ref.EditBatch), out=Ref.EditAck),
        method("changes", role="out", shape="log",
               params=Params(project_id=STR, graph_id=STR), out=Ref.AcceptedChange)),
    MediaKind=Enum(video=1, audio=2, text=3),
    NodeKind=Enum(source=1, effect=2, composite=3, transition=4, title=5, output=6, silence=7),
    ParamKind=Enum(integer=1, rational=2, boolean=3, text=4),
    EditKind=Enum(put_node=1, remove_node=2, put_edge=3, remove_edge=4,
                  put_track=5, remove_track=6, put_sequence=7, remove_sequence=8,
                  put_slot=9, remove_slot=10),
    AckStatus=Enum(accepted=1, duplicate=2, stale=3, invalid=4),
    Rational=Msg(numerator=F(1, INT), denominator=F(2, INT), next_id=3),
    TimeRange=Msg(start=F(1, Ref.Rational), end=F(2, Ref.Rational), next_id=3),
    ParamValue=Msg(kind=F(1, Ref.ParamKind), integer=F(2, INT, optional=True),
                   rational=F(3, Ref.Rational, optional=True), boolean=F(4, BOOL, optional=True),
                   text=F(5, STR, optional=True), next_id=6),
    SourcePayload=Msg(slot_id=F(1, STR), stream_id=F(2, STR),
                      source_range=F(3, Ref.TimeRange), speed=F(4, Ref.Rational), next_id=5),
    EffectPayload=Msg(effect_id=F(1, STR), effect_version=F(2, INT),
                      params=F(3, Map(STR, Ref.ParamValue)), next_id=4),
    CompositePayload=Msg(blend_id=F(1, STR), next_id=2),
    TransitionPayload=Msg(transition_id=F(1, STR), transition_version=F(2, INT),
                          params=F(3, Map(STR, Ref.ParamValue)), next_id=4),
    TitlePayload=Msg(text=F(1, STR), style_id=F(2, STR), next_id=3),
    OutputPayload=Msg(output_media=F(1, Ref.MediaKind), next_id=2),
    Node=Msg(id=F(1, STR), kind=F(2, Ref.NodeKind), media=F(3, Ref.MediaKind),
             sequence_id=F(4, STR), track_id=F(5, STR, optional=True),
             timeline_range=F(6, Ref.TimeRange, optional=True),
             source=F(7, Ref.SourcePayload, optional=True),
             effect=F(8, Ref.EffectPayload, optional=True),
             composite=F(9, Ref.CompositePayload, optional=True),
             transition=F(10, Ref.TransitionPayload, optional=True),
             title=F(11, Ref.TitlePayload, optional=True),
             output=F(12, Ref.OutputPayload, optional=True), next_id=13),
    Edge=Msg(id=F(1, STR), from_node=F(2, STR), from_port=F(3, STR),
             to_node=F(4, STR), to_port=F(5, STR),
             order_key=F(6, STR, optional=True), next_id=7),
    Track=Msg(id=F(1, STR), sequence_id=F(2, STR), media=F(3, Ref.MediaKind),
              order_key=F(4, STR), enabled=F(5, BOOL), next_id=6),
    Sequence=Msg(id=F(1, STR), video_root=F(2, STR, optional=True),
                 audio_root=F(3, STR, optional=True),
                 range=F(4, Ref.TimeRange), next_id=5),
    AssetSlot=Msg(id=F(1, STR), expected_media=F(2, Ref.MediaKind),
                  expected_duration=F(3, Ref.Rational, optional=True),
                  expected_fingerprint=F(4, STR, optional=True), next_id=5),
    GraphSnapshot=Msg(schema_major=F(1, INT), schema_minor=F(2, INT),
        graph_id=F(3, STR), project_id=F(4, STR), revision=F(5, INT),
        semantic_version=F(6, INT), sequences=F(7, Map(STR, Ref.Sequence)),
        tracks=F(8, Map(STR, Ref.Track)), nodes=F(9, Map(STR, Ref.Node)),
        edges=F(10, Map(STR, Ref.Edge)), slots=F(11, Map(STR, Ref.AssetSlot)), next_id=12),
    GraphSemantics=Msg(schema_major=F(1, INT), schema_minor=F(2, INT),
        semantic_version=F(3, INT), sequences=F(4, Map(STR, Ref.Sequence)),
        tracks=F(5, Map(STR, Ref.Track)), nodes=F(6, Map(STR, Ref.Node)),
        edges=F(7, Map(STR, Ref.Edge)), slots=F(8, Map(STR, Ref.AssetSlot)), next_id=9),
    EditOperation=Msg(kind=F(1, Ref.EditKind), target_id=F(2, STR),
        node=F(3, Ref.Node, optional=True), edge=F(4, Ref.Edge, optional=True),
        track=F(5, Ref.Track, optional=True), sequence=F(6, Ref.Sequence, optional=True),
        slot=F(7, Ref.AssetSlot, optional=True), next_id=8),
    EditBatch=Msg(project_id=F(1, STR), graph_id=F(2, STR), command_id=F(3, STR),
        expected_revision=F(4, INT), undo_group_id=F(5, STR),
        operations=F(6, List(Ref.EditOperation)), next_id=7),
    AffectedInterval=Msg(sequence_id=F(1, STR), range=F(2, Ref.TimeRange), next_id=3),
    ChangeFootprint=Msg(intervals=F(1, List(Ref.AffectedInterval)),
        node_ids=F(2, List(STR)), slot_ids=F(3, List(STR)),
        full_invalidation=F(4, BOOL), next_id=5),
    EditAck=Msg(command_id=F(1, STR), status=F(2, Ref.AckStatus),
        revision=F(3, INT), semantic_digest=F(4, STR, optional=True),
        reason=F(5, STR, optional=True), footprint=F(6, Ref.ChangeFootprint, optional=True),
        next_id=7),
    AcceptedChange=Msg(graph_id=F(1, STR), command_id=F(2, STR),
        from_revision=F(3, INT), to_revision=F(4, INT),
        operations=F(5, List(Ref.EditOperation)), footprint=F(6, Ref.ChangeFootprint), next_id=7),
)
